spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pase_db
    username: owner
    password: Owner123
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect